import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { 
  IsEmail, 
  IsNotEmpty, 
  IsString, 
  IsUUID, 
  IsOptional, 
  MinLength,
  IsUrl,
  IsPhoneNumber,
  Length
} from 'class-validator';

/* ======================================================
   1. ORGANISATION SIGNUP REQUEST (AUTH SERVICE)
   - Used for the public-facing signup API.
   - Includes Password but NO adminUserUuid.
====================================================== */

export class OrganisationSignupRequestDto {
  // --- ORGANIZATION DETAILS ---
  @ApiProperty({
    description: 'The registered legal name of the business or organization',
    example: 'Pivota Tech Solutions',
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(3)
  name!: string;

  @ApiProperty({
    description: 'General contact email for the business entity',
    example: 'info@pivotatech.co.ke',
  })
  @IsEmail()
  @IsNotEmpty()
  officialEmail!: string;

  @ApiProperty({
    description: 'General company contact number (International format)',
    example: '+254201234567',
  })
  @IsNotEmpty()
  @IsPhoneNumber(undefined, { message: 'Invalid official company phone number' })
  officialPhone!: string; // 👈 Added for business profile

  @ApiProperty({
    description: 'Physical location or headquarters of the organization',
    example: 'Waiyaki Way, Nairobi, Kenya',
  })
  @IsString()
  @IsNotEmpty()
  physicalAddress!: string;

  // --- ADMIN ACCOUNT DETAILS ---
  @ApiProperty({
    description: 'Login email for the organization admin',
    example: 'admin@pivotatech.co.ke',
  })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @ApiProperty({
    description: 'Password for the organization admin account',
    example: 'StrongPass@123',
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(8)
  password!: string;

  @ApiProperty({
    description: 'International phone number for the admin. Must include country code.',
    example: '+254711222333',
  })
  @IsNotEmpty()
  @IsPhoneNumber(undefined, { 
    message: 'Phone number must be valid and include a country code (e.g., +254...)' 
  })
  phone!: string;

  @ApiProperty({ description: 'Admin first name', example: 'John' })
  @IsString()
  @IsNotEmpty()
  adminFirstName!: string;

  @ApiProperty({ description: 'Admin last name', example: 'Doe' })
  @IsString()
  @IsNotEmpty()
  adminLastName!: string;

  @IsString()
  @Length(6, 6, { message: 'Verification code must be exactly 6 digits' })
  @IsNotEmpty()
  code!: string;
}

/* ======================================================
   2. CREATE ORGANISATION REQUEST (ORGANISATION SERVICE)
   - Used for internal gRPC/Service communication.
   - Includes adminUserUuid but NO Password.
====================================================== */
export class CreateOrganisationRequestDto {
  // --- Organization Identity ---
  @ApiProperty({
    description: 'The registered legal name of the business or organization',
    example: 'Pivota Tech Solutions',
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(3)
  name!: string;

  @ApiProperty({
    description: 'General contact email for the business entity',
    example: 'info@pivotatech.co.ke',
  })
  @IsEmail()
  @IsNotEmpty()
  officialEmail!: string; // 👈 Added

  @ApiProperty({
    description: 'General company contact number',
    example: '+254201234567',
  })
  @IsNotEmpty()
  @IsPhoneNumber(undefined)
  officialPhone!: string; // 👈 Added

  @ApiProperty({
    description: 'Physical location of the primary business office',
    example: 'Waiyaki Way, Nairobi, Kenya',
  })
  @IsString()
  @IsNotEmpty()
  physicalAddress!: string; // 👈 Added

  // --- Admin Mapping ---
  @ApiProperty({
    description: 'The UUID pre-generated by Auth Service to anchor identity',
    example: 'd9b2b1c0-1234-4a5b-8c9d-0123456789ab',
  })
  @IsUUID()
  @IsNotEmpty()
  adminUserUuid!: string;

  @ApiProperty({
    description: 'Login email for the admin (to populate the User table)',
    example: 'admin@pivotatech.co.ke',
  })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @ApiProperty({ 
    description: 'Admin phone number', 
    example: '+254711222333' 
  })
  @IsPhoneNumber(undefined)
  @IsNotEmpty()
  phone!: string; // 👈 Added to populate User.phone

  @ApiProperty({ description: 'Admin first name', example: 'John' })
  @IsString()
  @IsNotEmpty()
  adminFirstName!: string;

  @ApiProperty({ description: 'Admin last name', example: 'Doe' })
  @IsString()
  @IsNotEmpty()
  adminLastName!: string;
}

/* ======================================================
   3. UPDATE ORGANISATION PROFILE REQUEST
====================================================== */
export class UpdateOrgProfileRequestDto {
  @ApiPropertyOptional({ 
    description: 'Official company website URL',
    example: 'https://pivotatech.co.ke' 
  })
  @IsOptional()
  @IsUrl()
  website?: string;

  @ApiPropertyOptional({ 
    description: 'Government-issued business registration number',
    example: 'PVT-REG-001' 
  })
  @IsOptional()
  @IsString()
  registrationNo?: string;

  @ApiPropertyOptional({ 
    description: 'Kenya Revenue Authority Personal Identification Number (KRA PIN)',
    example: 'P051234567X' 
  })
  @IsOptional()
  @IsString()
  kraPin?: string;

  @ApiPropertyOptional({ 
    description: 'Physical location of the primary business office',
    example: 'Nairobi, Kenya' 
  })
  @IsOptional()
  @IsString()
  physicalAddress?: string;
}

/* ======================================================
   4. ADD ORGANISATION MEMBER REQUEST
====================================================== */
export class AddOrgMemberRequestDto {
  @ApiProperty({
    description: 'Global identifier of the organization',
    example: 'org_550e8400',
  })
  @IsUUID()
  @IsNotEmpty()
  orgUuid!: string;

  @ApiProperty({
    description: 'UUID of the user being added to the organization',
    example: 'user_a7164466',
  })
  @IsUUID()
  @IsNotEmpty()
  userUuid!: string;

  @ApiProperty({
    description: 'Role name to be assigned to the new member',
    example: 'FINANCE_MANAGER',
  })
  @IsString()
  @IsNotEmpty()
  role!: string;
}