import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { 
  IsEmail, 
  IsNotEmpty, 
  IsString, 
  IsUUID, 
  IsOptional, 
  MinLength,
  IsUrl,
  IsPhoneNumber,
  Length,
  IsIn
} from 'class-validator';


const ALLOWED_ORG_TYPES = [
  'PRIVATE_LIMITED', 
  'NGO', 
  'SOLE_PROPRIETORSHIP', 
  'GOVERNMENT', 
  'PARTNERSHIP'
];

/* ======================================================
   1. ORGANISATION SIGNUP REQUEST (AUTH SERVICE)
   - Used for the public-facing signup API.
   - Includes Password but NO adminUserUuid.
====================================================== */

export class OrganisationSignupRequestDto {
  // --- ORGANIZATION DETAILS ---
  @ApiProperty({
    description: 'The registered legal name of the business or organization',
    example: 'Pivota Tech Solutions',
    minLength: 3,
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(3)
  name!: string;
  

  @ApiProperty({
    description: 'General contact email for the business entity',
    example: 'info@pivotatech.co.ke',
  })
  @IsEmail()
  @IsNotEmpty()
  officialEmail!: string;

  @ApiProperty({
    description: 'General company contact number (International format)',
    example: '+254201234567',
  })
  @IsNotEmpty()
  @IsPhoneNumber(undefined, { message: 'Invalid official company phone number' })
  officialPhone!: string;

  @ApiProperty({
    description: 'Physical location or headquarters of the organization',
    example: 'Waiyaki Way, Nairobi, Kenya',
  })
  @IsString()
  @IsNotEmpty()
  physicalAddress!: string;

  // --- ADMIN ACCOUNT DETAILS ---
  @ApiProperty({
    description: 'Login email for the organization admin. This will be the primary identity.',
    example: 'admin@pivotatech.co.ke',
  })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @ApiProperty({
    description: 'Secure password for the admin account',
    example: 'StrongPass@123',
    minLength: 8,
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(8)
  password!: string;

  @ApiProperty({
    description: 'International phone number for the admin.',
    example: '+254711222333',
  })
  @IsNotEmpty()
  @IsPhoneNumber(undefined, { 
    message: 'Phone number must be valid and include a country code (e.g., +254...)' 
  })
  phone!: string;

  @ApiProperty({ description: 'Admin legal first name', example: 'John' })
  @IsString()
  @IsNotEmpty()
  adminFirstName!: string;

  @ApiProperty({ description: 'Admin legal last name', example: 'Doe' })
  @IsString()
  @IsNotEmpty()
  adminLastName!: string;

  @ApiProperty({
    description: '6-digit OTP verification code sent to the admin email',
    example: '123456',
    minLength: 6,
    maxLength: 6
  })
  @IsString()
  @Length(6, 6, { message: 'Verification code must be exactly 6 digits' })
  @IsNotEmpty()
  code!: string;

  @ApiProperty({
    description: 'The legal structure of the organization',
    enum: ALLOWED_ORG_TYPES,
    example: 'PRIVATE_LIMITED',
  })
  @IsNotEmpty()
  @IsString()
  @IsIn(ALLOWED_ORG_TYPES, {
    message: `organizationType must be one of: ${ALLOWED_ORG_TYPES.join(', ')}`
  })
  organizationType!: string;

  @ApiPropertyOptional({
    description: 'Target subscription plan. If not the free-plan, signup will return a payment redirect.',
    example: 'org-premium-tier',
    default: 'free-plan'
  })
  @IsOptional()
  @IsString()
  planSlug?: string; 
}

/* ======================================================
   2. CREATE ORGANISATION REQUEST (ORGANISATION SERVICE)
   - Used for internal gRPC/Service communication.
   - Includes adminUserUuid but NO Password.
====================================================== */
export class CreateOrganisationRequestDto {
  // --- Organization Identity ---
  @ApiProperty({
    description: 'The registered legal name of the business or organization',
    example: 'Pivota Tech Solutions',
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(3)
  name!: string;

  @ApiProperty({
    description: 'General contact email for the business entity',
    example: 'info@pivotatech.co.ke',
  })
  @IsEmail()
  @IsNotEmpty()
  officialEmail!: string; // 👈 Added

  @ApiProperty({
    description: 'General company contact number',
    example: '+254201234567',
  })
  @IsNotEmpty()
  @IsPhoneNumber(undefined)
  officialPhone!: string; // 👈 Added

  @ApiProperty({
    description: 'Physical location of the primary business office',
    example: 'Waiyaki Way, Nairobi, Kenya',
  })
  @IsString()
  @IsNotEmpty()
  physicalAddress!: string; // 👈 Added

  // --- Admin Mapping ---
  @ApiProperty({
    description: 'The UUID pre-generated by Auth Service to anchor identity',
    example: 'd9b2b1c0-1234-4a5b-8c9d-0123456789ab',
  })
  @IsUUID()
  @IsNotEmpty()
  adminUserUuid!: string;

  @ApiProperty({
    description: 'Login email for the admin (to populate the User table)',
    example: 'admin@pivotatech.co.ke',
  })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @ApiProperty({ 
    description: 'Admin phone number', 
    example: '+254711222333' 
  })
  @IsPhoneNumber(undefined)
  @IsNotEmpty()
  phone!: string; // 👈 Added to populate User.phone

  @ApiProperty({ description: 'Admin first name', example: 'John' })
  @IsString()
  @IsNotEmpty()
  adminFirstName!: string;

  @ApiProperty({ description: 'Admin last name', example: 'Doe' })
  @IsString()
  @IsNotEmpty()
  adminLastName!: string;

  @ApiProperty({
    description: 'The type of organization',
    example: 'PRIVATE_LIMITED',
  })
  @IsNotEmpty()
  @IsString()
  @IsIn(ALLOWED_ORG_TYPES)
  organizationType!: string;

  @ApiPropertyOptional({
    description: 'The subscription plan for the organization',
    example: 'free-plan',
  })
  @IsString()
  planSlug!: string; // mandatory here
}

/* ======================================================
   3. UPDATE ORGANISATION PROFILE REQUEST
====================================================== */
export class UpdateOrgProfileRequestDto {
  @ApiPropertyOptional({ 
    description: 'Official company website URL',
    example: 'https://pivotatech.co.ke' 
  })
  @IsOptional()
  @IsUrl()
  website?: string;

  @ApiPropertyOptional({ 
    description: 'Government-issued business registration number',
    example: 'PVT-REG-001' 
  })
  @IsOptional()
  @IsString()
  registrationNo?: string;

  @ApiPropertyOptional({ 
    description: 'Kenya Revenue Authority Personal Identification Number (KRA PIN)',
    example: 'P051234567X' 
  })
  @IsOptional()
  @IsString()
  kraPin?: string;

  @ApiPropertyOptional({ 
    description: 'Physical location of the primary business office',
    example: 'Nairobi, Kenya' 
  })
  @IsOptional()
  @IsString()
  physicalAddress?: string;

  @ApiPropertyOptional({ 
    description: 'Update the legal structure',
    enum: ALLOWED_ORG_TYPES 
  })
  @IsOptional()
  @IsString()
  @IsIn(ALLOWED_ORG_TYPES)
  organizationType?: string;
}

/* ======================================================
   4. ADD ORGANISATION MEMBER REQUEST (Direct Link)
====================================================== */
export class AddOrgMemberRequestDto {
  @ApiProperty({
    description: 'Global identifier of the organization',
    example: 'd9b2b1c0-1234-4a5b-8c9d-0123456789ab',
  })
  @IsUUID()
  @IsNotEmpty()
  orgUuid!: string;

  @ApiProperty({
    description: 'UUID of the user being added to the organization',
    example: 'a7164466-1234-4a5b-8c9d-0123456789ab',
  })
  @IsUUID()
  @IsNotEmpty()
  userUuid!: string;

  @ApiProperty({
    description: 'Role name to be assigned to the new member',
    example: 'FinanceManager',
  })
  @IsString()
  @IsNotEmpty()
  role!: string;
}

/* ======================================================
   5. INVITE MEMBER REQUEST (Email-Based Invitation)
   - Used by the Gateway to trigger the invitation flow.
====================================================== */
export class InviteMemberRequestDto {
  @ApiProperty({
    description: 'The organization the user is being invited to',
    example: 'd9b2b1c0-1234-4a5b-8c9d-0123456789ab',
  })
  @IsUUID()
  @IsNotEmpty()
  orgUuid!: string;

  @ApiProperty({
    description: 'The email address of the person being invited',
    example: 'colleague@example.com',
  })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @ApiProperty({
    description: 'The role they will assume upon joining',
    example: 'Member',
  })
  @IsString()
  @IsNotEmpty()
  roleName!: string;

  // This is usually extracted from the JWT in the Controller, 
  // but included here for gRPC internal transport.
  @IsUUID()
  @IsOptional()
  invitedByUuid?: string;
}

/* ======================================================
   6. MEMBER INVITED EVENT DTO (Notification Service)
   - Used for the 'member.invited' event on the Event Bus.
====================================================== */
export class MemberInviteEventDto {
  @IsEmail()
  email!: string;

  @IsString()
  orgName!: string;

  @IsString()
  role!: string;

  @IsString()
  inviteToken!: string;

  @IsString()
  joinUrl!: string;

  @IsUUID()
  invitedByUuid!: string;
}


/* ======================================================
   7. ACCEPT INVITATION REQUEST
====================================================== */
export class AcceptInvitationRequestDto {
  @ApiProperty({
    description: 'The unique secret token sent to the users email',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  @IsString()
  @IsNotEmpty()
  // If you use UUIDs for tokens, you can use @IsUUID() here
  token!: string;
}