import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import { 
  IsArray, 
  IsBoolean, 
  IsNotEmpty, 
  IsOptional, 
  IsString, 
  IsEmail, 
  IsUUID, 
  MinLength,
  IsDateString,
  IsUrl,
  Length,
  Matches,
  ValidateIf,
  IsInt,
  Min
} from 'class-validator';

/**
 * Kenyan Phone Regex:
 * Supports: +254..., 254..., 07..., 01..., 02...
 */
export const KENYAN_PHONE_REGEX = /^(?:254|\+254|0)?((?:7|1|2)\d{8})$/;

/* ======================================================
   BASE SCHEMA (Shared update properties)
====================================================== */

export abstract class BaseUpdateProfileDto {
  @ApiPropertyOptional({ 
    description: 'The first name of the user',
    example: 'Jane' 
  })
  @IsOptional()
  @IsString()
  firstName?: string;

  @ApiPropertyOptional({ 
    description: 'The last name of the user',
    example: 'Doe' 
  })
  @IsOptional()
  @IsString()
  lastName?: string;

  @ApiPropertyOptional({ 
    description: 'The primary email address',
    example: 'jane.doe@pivota.com' 
  })
  @IsOptional()
  @ValidateIf((o) => o.email && o.email.trim() !== '')  
  @IsEmail()
  email?: string;

  @ApiPropertyOptional({ 
    description: 'Kenyan phone number in international or local format',
    example: '+254712345678' 
  })
  @IsOptional()
  @ValidateIf((o) => o.phone !== '' && o.phone !== null && o.phone !== undefined)
  @Matches(KENYAN_PHONE_REGEX, { 
    message: 'Please provide a valid Kenyan phone number' 
  })
  phone?: string;

  @ApiPropertyOptional({ 
    description: 'A short professional or personal bio',
    example: 'Software Engineer based in Nairobi.' 
  })
  @IsOptional()
  @IsString()
  bio?: string;

  @ApiPropertyOptional({ 
    description: 'The biological gender identity',
    example: 'FEMALE',
    enum: ['MALE', 'FEMALE', 'OTHER']
  })
  @IsOptional()
  @IsString()
  gender?: string;

  @ApiPropertyOptional({ 
    description: 'Date of birth in ISO 8601 format',
    example: '1995-05-15' 
  })
  @IsOptional()
  @ValidateIf((o) => o.dateOfBirth && o.dateOfBirth.trim() !== '')
  @IsDateString({}, { 
    message: 'dateOfBirth must be a valid ISO 8601 date string' 
  })
  dateOfBirth?: string;

  @ApiPropertyOptional({ 
    description: 'Government-issued National ID or Passport number',
    example: '32145678' 
  })
  @IsOptional()
  @IsString()
  nationalId?: string;
}

/* ======================================================
   PUBLIC GATEWAY DTOs (Own vs Admin)
====================================================== */

export class UpdateOwnProfileRequestDto extends BaseUpdateProfileDto {}

export class UpdateAdminProfileRequestDto extends BaseUpdateProfileDto {
  @ApiProperty({ 
    description: 'The unique system identifier (UUID) of the user to update',
    example: '550e8400-e29b-41d4-a716-446655440000'
  })
  @IsUUID()
  @IsNotEmpty()
  userUuid!: string;
}

/* ======================================================
   INTERNAL / gRPC DTOs
====================================================== */

export class UpdateFullUserProfileDto extends BaseUpdateProfileDto {
  @ApiProperty({ 
    description: 'The unique system identifier (UUID) of the target user',
    example: '550e8400-e29b-41d4-a716-446655440000'
  })
  @IsUUID()
  @IsNotEmpty()
  userUuid!: string;

  @ApiPropertyOptional({
    description: 'The public URL for the uploaded profile avatar generated by the gateway',
    example: 'https://cdn.pivota.com/profiles/u123/avatar.jpg'
  })
  @IsOptional()
  @IsUrl()
  profileImage?: string;
}

/* ======================================================
   CREATION DTOs (Auth & Profile)
====================================================== */

export class UserSignupRequestDto {
  @ApiProperty({ description: 'Legal first name', example: 'Jane' })
  @IsString()
  @IsNotEmpty()
  firstName!: string;

  @ApiProperty({ description: 'Legal last name', example: 'Doe' })
  @IsString()
  @IsNotEmpty()
  lastName!: string;

  @ApiProperty({ description: 'Unique email address for login', example: 'jane.doe@pivota.com' })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @ApiPropertyOptional({ description: 'Valid Kenyan mobile number', example: '0712345678' })
  @IsOptional()
  @Matches(KENYAN_PHONE_REGEX)
  phone?: string;

  @ApiProperty({ 
    description: 'Secure password (min 8 characters)', 
    example: 'StrongPass@2026', 
    minLength: 8 
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(8)
  password!: string;

  @ApiPropertyOptional({ description: 'Subscription plan slug', example: 'premium-business' })
  @IsString()
  @IsOptional()
  planSlug?: string;

  @ApiProperty({ description: '6-digit OTP code', example: '123456' })
  @IsString()
  @Length(6, 6)
  @IsNotEmpty()
  code!: string;
}

export class CreateUserRequestDto {
  @ApiProperty({ description: 'UUID from Auth Service' })
  @IsUUID()
  @IsNotEmpty()
  userUuid!: string;

  @ApiProperty({ example: 'Jane' })
  @IsString()
  @IsNotEmpty()
  firstName!: string;

  @ApiProperty({ example: 'Doe' })
  @IsString()
  @IsNotEmpty()
  lastName!: string;

  @ApiProperty({ example: 'jane.doe@pivota.com' })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @ApiPropertyOptional({ example: '0712345678' })
  @IsOptional()
  @Matches(KENYAN_PHONE_REGEX)
  phone?: string;

  @ApiProperty({ example: 'free-tier' })
  @IsString()
  @IsNotEmpty()
  planSlug!: string;
}

/* ======================================================
   SERVICE PROVIDER (CONTRACTOR) ONBOARDING
====================================================== */

export class OnboardIndividualProviderRequestDto {
  @ApiProperty({ 
    description: 'Professional specialties. Can be sent as a comma-separated string in form-data.',
    example: ['Plumbing', 'Electrical'],
    type: [String]
  })
  @IsArray()
  @IsString({ each: true })
  @IsNotEmpty({ each: true })
  specialties!: string[];

  @ApiProperty({ 
    description: 'Areas served. Can be sent as a comma-separated string in form-data.',
    example: ['Nairobi West', 'Langata'],
    type: [String]
  })
  @IsArray()
  @IsString({ each: true })
  @IsNotEmpty({ each: true })
  serviceAreas!: string[];

  @ApiProperty({ description: 'Years of professional experience', example: 5 })
  @IsInt()
  @Min(0)
  yearsExperience!: number;
}

export class OnboardProviderGrpcRequestDto extends OnboardIndividualProviderRequestDto {
  @ApiProperty({ description: 'Target user UUID' })
  @IsUUID()
  @IsNotEmpty()
  userUuid!: string;
}

/* ======================================================
   JOB SEEKER (CAREER) DTOs
====================================================== */

export class UpdateJobSeekerRequestDto {
  @ApiPropertyOptional({ 
    description: 'Professional headline for the job market',
    example: 'Senior Full Stack Developer | NestJS & React' 
  })
  @IsOptional()
  @IsString()
  headline?: string;

  @ApiProperty({ 
    description: 'Visibility status for the recommender engine. In form-data, use "true" or "false".',
    example: true 
  })
  @IsNotEmpty()
  @Transform(({ value }) => value === 'true' || value === true)
  @IsBoolean()
  isActivelySeeking!: boolean;

  @ApiPropertyOptional({ 
    description: 'Core professional skills. Supports comma-separated strings in form-data.',
    example: ['Node.js', 'PostgreSQL'],
    type: [String]
  })
  @IsOptional()
  @Transform(({ value }) => {
    if (Array.isArray(value)) return value;
    if (typeof value === 'string') return value.split(',').map(s => s.trim());
    return value;
  })
  @IsArray()
  @IsString({ each: true })
  skills?: string[];

  @ApiPropertyOptional({ 
    description: 'Target industries for career matching.',
    example: ['FinTech', 'Real Estate'],
    type: [String]
  })
  @IsOptional()
  @Transform(({ value }) => {
    if (Array.isArray(value)) return value;
    if (typeof value === 'string') return value.split(',').map(s => s.trim());
    return value;
  })
  @IsArray()
  @IsString({ each: true })
  industries?: string[];

  @ApiPropertyOptional({ 
    description: 'Experience level',
    example: 'SENIOR',
    enum: ['ENTRY', 'INTERMEDIATE', 'SENIOR', 'LEAD', 'EXECUTIVE']
  })
  @IsOptional()
  @IsString()
  seniorityLevel?: string;

  @ApiPropertyOptional({ 
    description: 'Preferred job contract types.',
    example: ['FULL_TIME', 'CONTRACT'],
    type: [String]
  })
  @IsOptional()
  @Transform(({ value }) => {
    if (Array.isArray(value)) return value;
    if (typeof value === 'string') return value.split(',').map(s => s.trim());
    return value;
  })
  @IsArray()
  @IsString({ each: true })
  jobTypes?: string[];
}

export class UpdateJobSeekerGrpcRequestDto extends UpdateJobSeekerRequestDto {
  @ApiProperty({ description: 'Target user UUID' })
  @IsUUID()
  @IsNotEmpty()
  userUuid!: string;

  @ApiPropertyOptional({
    description: 'Private URL for the uploaded CV document',
    example: 'https://storage.pivota.com/cvs/user-123.pdf'
  })
  @IsOptional()
  @IsUrl()
  cvUrl?: string;
}