import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { 
  IsEmail, 
  IsNotEmpty, 
  IsString, 
  IsUUID, 
  IsOptional, 
  MinLength,
  IsPhoneNumber,
  IsDateString,
  IsUrl,
  Length
} from 'class-validator';

/* ======================================================
   1. USER SIGNUP REQUEST (AUTH SERVICE)
   - Used for the public-facing individual signup API.
   - Includes Password but NO userUuid (Auth generates this).
====================================================== */

export class UserSignupRequestDto {
  @ApiProperty({ 
    description: 'Legal first name of the user', 
    example: 'Jane' 
  })
  @IsString()
  @IsNotEmpty()
  firstName!: string;

  @ApiProperty({ 
    description: 'Legal last name of the user', 
    example: 'Doe' 
  })
  @IsString()
  @IsNotEmpty()
  lastName!: string;

  @ApiProperty({
    description: 'Unique login email address',
    example: 'jane.doe@pivota.com',
  })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @ApiProperty({
    description: 'International format phone number',
    example: '+254700111222',
  })
  @IsNotEmpty()
  @IsPhoneNumber(undefined, { message: 'Invalid phone number format' })
  phone!: string;

  @ApiProperty({
    description: 'Secure password (minimum 8 characters)',
    example: 'StrongPass@2026',
    minLength: 8,
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(8)
  password!: string;

  @ApiPropertyOptional({
    description: 'Target subscription tier. Defaults to free-forever if not provided.',
    example: 'business-pro',
    enum: ['free-forever', 'business-pro', 'contractor-premium'],
    default: 'free-forever'
  })
  @IsString()
  @IsOptional()
  planSlug?: string;

  @ApiProperty({
    description: '6-digit OTP received via email/SMS',
    example: '123456',
    minLength: 6,
    maxLength: 6
  })
  @IsString()
  @Length(6, 6, { message: 'Verification code must be exactly 6 digits' })
  @IsNotEmpty()
  code!: string;
}

/* ======================================================
   2. CREATE USER REQUEST (PROFILE SERVICE)
   - Used for internal gRPC/Service communication.
   - Includes userUuid from Auth but NO Password.
====================================================== */

export class CreateUserRequestDto {
  @ApiProperty({
    description: 'The UUID pre-generated by Auth Service to anchor identity',
    example: 'u-1234-uuid-5678',
  })
  @IsUUID()
  @IsNotEmpty()
  userUuid!: string;

  @ApiProperty({ example: 'Jane' })
  @IsString()
  @IsNotEmpty()
  firstName!: string;

  @ApiProperty({ example: 'Doe' })
  @IsString()
  @IsNotEmpty()
  lastName!: string;

  @ApiProperty({ example: 'jane.doe@pivota.com' })
  @IsEmail()
  @IsNotEmpty()
  email!: string;

  @ApiProperty({ example: '+254700111222' })
  @IsPhoneNumber(undefined)
  @IsNotEmpty()
  phone!: string;

  @IsString()
  @IsNotEmpty()
  planSlug!: string; // Mandatory here
}

/* ======================================================
   3. UPDATE USER PROFILE REQUEST
   - Maps to the UserProfile metadata table.
====================================================== */

export class UpdateUserProfileRequestDto {
  @ApiPropertyOptional({ 
    description: 'Short professional or personal biography',
    example: 'Software Engineer based in Nairobi.' 
  })
  @IsOptional()
  @IsString()
  bio?: string;

  @ApiPropertyOptional({ 
    description: 'Biological gender identity',
    example: 'FEMALE'
  })
  @IsOptional()
  @IsString()
  gender?: string;

  @ApiPropertyOptional({ 
    description: 'Date of birth for age verification (ISO Format)',
    example: '1995-05-15T00:00:00Z' 
  })
  @IsOptional()
  @IsDateString()
  dateOfBirth?: string;

  @ApiPropertyOptional({ 
    description: 'Government-issued National ID or Passport number',
    example: '32145678' 
  })
  @IsOptional()
  @IsString()
  nationalId?: string;

  @ApiPropertyOptional({
    description: 'URL to the user profile avatar/image',
    example: 'https://cdn.pivota.com/profiles/u123.jpg'
  })
  @IsOptional()
  @IsUrl()
  profileImage?: string;
}

/* ======================================================
   4. FULL USER PROFILE UPDATE (UNIFIED)
   - Used for the Gateway to update both User and Profile tables.
====================================================== */

export class UpdateFullUserProfileDto extends UpdateUserProfileRequestDto {
  @ApiProperty({ description: 'The UUID of the user to update' })
  @IsUUID()
  @IsNotEmpty()
  userUuid!: string;

  @ApiPropertyOptional({ example: 'Jane' })
  @IsOptional()
  @IsString()
  firstName?: string;

  @ApiPropertyOptional({ example: 'Doe' })
  @IsOptional()
  @IsString()
  lastName?: string;

  @ApiPropertyOptional({ example: 'jane.doe@pivota.com' })
  @IsOptional()
  @IsEmail()
  email?: string;

  @ApiPropertyOptional({ example: '+254700111222' })
  @IsOptional()
  @IsPhoneNumber(undefined)
  phone?: string;
}